### ISSUE TITLE
Comments not auto-reloading after first comment is placed (solved)

### ISSUE THREAD

**Issue by dwrolvink** [konishi-project/higala#1]
Hi, I don't know if I should make a pull request for this (as it's a one line change). And I'm not sure if the fix is completely supported, because I'm still getting a feel for the app, so here is the issue description and its solution at least.

If I need to just save all these little issues and make a pull request for a load of fixes in one go, let me know.

## Issue: 
If you post a comment on a post, the comment is not shown directly, you have to reload the page before it becomes visible. This is not the case if there are already comments on the post.

## Analysis:  
I tracked the problem to the following code: (Post.vue)
```
<div v-if="post.comments.length > 0" class="pr4 pl4">
        (...)
</div>
```

and 

```
 commentOnPost() {
        (...)
        .then(response => {
          if (response.status === 200) {
            // Add the comment
            let new_comment = response.data.new_comment;
            this.comments = this.comments + 1;
            this.comments_info.push(new_comment);
          }
        })
        (...)
    },
```
When commentOnPost() is called, it pushes the new comment to this.comments_info, but not to post.comments. So, when you push the new comment, the v-if is not re evaluated, causing the comments to stay hidden.

## Resolution:
Either 
  * add `this.post.comments.length++;` to the end of commentOnPost()

or (as I preferred), 

  * change `v-if="post.comments.length > 0"` to `v-if="this.comments_info.length > 0"`

**Comment by X1Zeth2X** [comment]
Fixed.
